[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["cd websocket-server && npm ci --production=false"]

[phases.build]
cmds = ["cd websocket-server && npm run build"]

[start]
cmd = "cd websocket-server && npm start"

[variables]
NODE_ENV = "production"