[build]
builder = "nixpacks"
buildCommand = "cd websocket-server && npm install && npm run build"

[deploy]
startCommand = "cd websocket-server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300